/* 
 * My API with Swagger
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: google@google.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductApiTests
    {
        private ProductApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductApi
            //Assert.IsInstanceOfType(typeof(ProductApi), instance, "instance is a ProductApi");
        }

        
        /// <summary>
        /// Test ApiProductByIdDelete
        /// </summary>
        [Test]
        public void ApiProductByIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiProductByIdDelete(id);
            
        }
        
        /// <summary>
        /// Test ApiProductByIdGet
        /// </summary>
        [Test]
        public void ApiProductByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiProductByIdGet(id);
            
        }
        
        /// <summary>
        /// Test ApiProductByIdPut
        /// </summary>
        [Test]
        public void ApiProductByIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string value = null;
            //instance.ApiProductByIdPut(id, value);
            
        }
        
        /// <summary>
        /// Test ApiProductGet
        /// </summary>
        [Test]
        public void ApiProductGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiProductGet();
            //Assert.IsInstanceOf<List<Product>> (response, "response is List<Product>");
        }
        
        /// <summary>
        /// Test ApiProductPost
        /// </summary>
        [Test]
        public void ApiProductPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //instance.ApiProductPost(value);
            
        }
        
        /// <summary>
        /// Test ApiProductSearchByValueGet
        /// </summary>
        [Test]
        public void ApiProductSearchByValueGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ApiProductSearchByValueGet(value);
            //Assert.IsInstanceOf<List<Product>> (response, "response is List<Product>");
        }
        
    }

}
