/* 
 * My API with Swagger
 *
 * A simple example ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: google@google.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValuesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ValuesApiTests
    {
        private ValuesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ValuesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValuesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ValuesApi
            //Assert.IsInstanceOfType(typeof(ValuesApi), instance, "instance is a ValuesApi");
        }

        
        /// <summary>
        /// Test ApiValuesByIdByNameGet
        /// </summary>
        [Test]
        public void ApiValuesByIdByNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string name = null;
            //var response = instance.ApiValuesByIdByNameGet(id, name);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ApiValuesByIdGet
        /// </summary>
        [Test]
        public void ApiValuesByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int? id = 2;
            var response = instance.ApiValuesByIdGet(id);
            Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ApiValuesByIdPut
        /// </summary>
        [Test]
        public void ApiValuesByIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            int? id = null;
            string value = null;
            instance.ApiValuesByIdPut(id, value);

        }
        
        /// <summary>
        /// Test ApiValuesGet
        /// </summary>
        [Test]
        public void ApiValuesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiValuesGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test ApiValuesPost
        /// </summary>
        [Test]
        public void ApiValuesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //instance.ApiValuesPost(value);
            
        }
        
    }

}
